defaults:
  - base_simulator

_target_: simulator.mujoco_simulator.MujocoSimulator
_recursive_: False
config:
  record_video: False
  marker: True
  joystick: False
  camera_follow: True
  estimate_root_pos: False  # global tracking: use the legged state estimator on simulated sensors instead of ground truth